---
require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Naming/FileName:
  Exclude:
    - lib/rubocop-fussy-pedant.rb

Gemspec/DevelopmentDependencies:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'
