---
FussyPedant/Ruby:
  Enabled: true

FussyPedant/Rails:
  Enabled: true

FussyPedant/RSpec:
  Enabled: true

FussyPedant/RSpec/NoWait:
  Enabled: true
  Include:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'

FussyPedant/RSpec/RequestSpecOrder:
  Enabled: true
  Include:
    - 'spec/requests/**/*.rb'
  RestActions:
    - index
    - show
    - new
    - create
    - edit
    - update
    - destroy

FussyPedant/RSpec/ModelSpecDescribeFormat:
  Enabled: true
  Include:
    - 'spec/models/**/*.rb'

FussyPedant/RSpec/ModelSpecMethodOrder:
  Enabled: true
  Include:
    - 'spec/models/**/*.rb'

FussyPedant/RSpec/ServiceDescribeCall:
  Enabled: true
  Include:
    - 'spec/services/**/*.rb'

FussyPedant/Rake:
  Enabled: true

FussyPedant/FactoryBot:
  Enabled: true

FussyPedant/FactoryBot/TraitsAlphabeticalOrder:
  Enabled: true
  Include:
    - 'spec/support/factories/**/*.rb'

FussyPedant/Ruby/CommentLineLength:
  Enabled: true
  MaxColumn: 72

FussyPedant/Ruby/ConsistentArrayCoercion:
  Enabled: true
  Description: 'Use a consistent array-coercion idiom.'
  EnforcedStyle: array_coercion
  SupportedStyles:
    - array_coercion
    - logical_or

FussyPedant/Ruby/ConstantDefinitionOrder:
  Enabled: true
  Description: 'Alphabetize constant definitions within a class or module.'

FussyPedant/Ruby/InitializeAssignmentOrder:
  Enabled: true
  Description: 'Alphabetize instance variable assignments in initialize.'

FussyPedant/Ruby/NoNamespaceAssignment:
  Enabled: true
  Description: 'Do not resolve constants through a local variable.'

FussyPedant/Ruby/NoNonAsciiInComment:
  Enabled: true
  Description: 'Avoid non-ASCII characters in comments.'

FussyPedant/Ruby/NoSingleLineCaseBody:
  Enabled: true
  Description: 'Move case/when/else body to the next line.'

FussyPedant/Ruby/NoTerminalGuardClause:
  Enabled: true
  Description: 'Use if/else or case/when instead of guard clause(s) before the final expression.'

FussyPedant/Ruby/SpaceInsidePercentArray:
  Enabled: true
  Description: 'Put a space inside the delimiters of a percent array.'

FussyPedant/Rails/AssociationOrder:
  Enabled: true
  CheckAlphabetical: true
  CheckSpacing: true
  Include:
    - 'app/models/**/*.rb'

FussyPedant/Rails/EnumOrder:
  Enabled: true
  CheckAlphabetical: true
  CheckOnePerLine: true
  Include:
    - 'app/models/**/*.rb'

FussyPedant/Rails/ServiceCallPattern:
  Enabled: true
  ServicesDirectory: ''
  Include:
    - 'app/services/**/*.rb'

FussyPedant/Rails/ControllerMethodOrder:
  Enabled: true
  Include:
    - 'app/controllers/**/*.rb'
  RestActions:
    - index
    - show
    - new
    - create
    - edit
    - update
    - destroy
