---
FussyPedant/Ruby:
  Enabled: true

FussyPedant/Rails:
  Enabled: true

FussyPedant/RSpec:
  Enabled: true

FussyPedant/RSpec/NoWait:
  Enabled: true
  Include:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'

FussyPedant/RSpec/RequestSpecOrder:
  Enabled: true
  Include:
    - 'spec/requests/**/*.rb'
  RestActions:
    - index
    - show
    - new
    - create
    - edit
    - update
    - destroy

FussyPedant/RSpec/ServiceDescribeCall:
  Enabled: true
  Include:
    - 'spec/services/**/*.rb'

FussyPedant/Rake:
  Enabled: true

FussyPedant/FactoryBot:
  Enabled: true

FussyPedant/FactoryBot/TraitsAlphabeticalOrder:
  Enabled: true
  Include:
    - 'spec/support/factories/**/*.rb'

FussyPedant/Ruby/CommentLineLength:
  Enabled: true
  MaxColumn: 72

FussyPedant/Rails/AssociationOrder:
  Enabled: true
  CheckAlphabetical: true
  CheckSpacing: true
  Include:
    - 'app/models/**/*.rb'

FussyPedant/Rails/EnumOrder:
  Enabled: true
  CheckAlphabetical: true
  CheckOnePerLine: true
  Include:
    - 'app/models/**/*.rb'

FussyPedant/Rails/ServiceCallPattern:
  Enabled: true
  ServicesDirectory: ''
  Include:
    - 'app/services/**/*.rb'

FussyPedant/Rails/ControllerMethodOrder:
  Enabled: true
  Include:
    - 'app/controllers/**/*.rb'
  RestActions:
    - index
    - show
    - new
    - create
    - edit
    - update
    - destroy
